version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gymplanner
      - POSTGRES_USER=gymplanner
      - POSTGRES_PASSWORD=gymplanner321
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_gymplanner
    restart: always
    logging:
      driver: none
    depends_on:
      - db
    ports:
      - '8085:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: andrey.andrade@wpengine.com
      PGADMIN_DEFAULT_PASSWORD: gymplanner321
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - ..:/pgadmin4/servers.json
      - ../workspace/db-pgadmin:/var/lib/pgadmin
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8005:8000"
    depends_on:
      - db